// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission_08Team3_10.Models;

#nullable disable

namespace Mission_08Team3_10.Migrations
{
    [DbContext(typeof(Mission08Context))]
    [Migration("20260227022322_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Mission_08Team3_10.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Home"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "School"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Work"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Church"
                        });
                });

            modelBuilder.Entity("Mission_08Team3_10.Models.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quadrant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            CategoryId = 1,
                            Completed = false,
                            DueDate = new DateOnly(2026, 3, 1),
                            Quadrant = 1,
                            TaskName = "Pay Bills"
                        },
                        new
                        {
                            TaskId = 2,
                            CategoryId = 2,
                            Completed = false,
                            DueDate = new DateOnly(2026, 3, 5),
                            Quadrant = 1,
                            TaskName = "Study for Exam"
                        },
                        new
                        {
                            TaskId = 3,
                            CategoryId = 1,
                            Completed = false,
                            Quadrant = 2,
                            TaskName = "Exercise"
                        },
                        new
                        {
                            TaskId = 4,
                            CategoryId = 4,
                            Completed = false,
                            Quadrant = 2,
                            TaskName = "Read Scriptures"
                        },
                        new
                        {
                            TaskId = 5,
                            CategoryId = 3,
                            Completed = false,
                            DueDate = new DateOnly(2026, 3, 1),
                            Quadrant = 3,
                            TaskName = "Answer Emails"
                        },
                        new
                        {
                            TaskId = 6,
                            Completed = false,
                            Quadrant = 4,
                            TaskName = "Browse Social Media"
                        });
                });

            modelBuilder.Entity("Mission_08Team3_10.Models.Task", b =>
                {
                    b.HasOne("Mission_08Team3_10.Models.Category", "Category")
                        .WithMany("Tasks")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Mission_08Team3_10.Models.Category", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
